### PR TITLE
Handle '.' in key normalization

### PR DESCRIPTION
**Pull request by doowb**
When a `'.'` is pressed, the `key` object does not contain a name. This check will return the `event` before checking if the key was a `return/enter` keypress to ensure that periods are emitted and shown in prompts.

Should we also add an `event.key.name = 'period';` here?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> Should we also add an event.key.name = 'period'; here?

I would do `dot` and `period`, I think because of the prevalence of `dot` in programming a lot of devs will think of that first.

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
> Should we also add an event.key.name = 'period'; here?

per my comment above, I was thinking you meant that we would fix the keypress events to emit `dot`. if we can do that, I think that's the best solution. Otherwise just go with what you were suggesting. 

edit: see https://github.com/enquirer/readline-utils/blob/master/index.js#L254

**Comment by doowb** [comment]
This change is inside the linked function.
I'll move the if statement up to be the first one so the regexp checks aren't done first and I'll name the event `dot` like we do [here](https://github.com/enquirer/readline-utils/blob/master/index.js#L260) for numbers.

> I was thinking you meant that we would fix the keypress events to emit `dot`

I don't think we're emitting individual key names, just `keypress` with the normalized event object, but we could add something like that so implementors can choose to listen for specific keypresses.

**Comment by doowb** [comment]
OIC... we are emitting the individual names [here](https://github.com/enquirer/readline-ui/blob/master/index.js#L61-L63).

What about leaving the `event.key.name` undefined here, and checking in `readline-ui` if the `sequence` is `.` then we emit both `dot` and `period` there?

**Comment by jonschlinkert** [comment]
I think we should just normalize the keypress events to support `period`. Wouldn't that solve it?

**Comment by doowb** [comment]
Yeah, that'll work.

**Comment by JohnCMcDonough** [comment]
I still encountered the issue of periods and single quotes not being displayed correctly in node 8, 7, and 6. I'm not sure which issue this goes under, so I figured I'd post it here.

Testing was done using readline-utils@2.2.1 and prompt-base@3.0.5.

The code used to test was taken from the prompt-base GitHub readme.
```
var Prompt = require('prompt-base');
var prompt = new Prompt({
  name: 'color',
  message: 'What is your favorite color?'
});

// promise
prompt.run()
  .then(function(answer) {
    console.log(answer);
    //=> 'blue'
  })
```

**Comment by doowb** [comment]
@JohnCMcDonough will you open a new issue here?

**Pull request merged**
